---
permalink: deploy/prepare-deployment.html
sidebar: sidebar
keywords:
summary: 'You should deploy ONTAP tools for VMware vSphere in your environment, and specify the required parameters, to be able to use the appliance.'
---
= Prepare to deploy ONTAP tools for VMware vSphere
:icons: font
:imagesdir: ../media/

[.lead]
You should be aware of the basic storage backend requirements, application requirements, and license requirements before you begin deploying ONTAP tools for VMware vSphere. 
Plan your deployment in advance and decide how you want to configure ONTAP tools for VMware vSphere in your environment. 

== Preparing for deployment 

Following are ONTAP tools for VMware vSphere requirements before proceeding with the deployment: 

. Configure and set up your vCenter Server environment. 
. Download the _.ova_ file. 
. (Optional) Used for automation user - Gather the Postman collections JSON file provided by NetApp. 
. Parent vCenter Server Credentials to deploy the OVA. Parent vCenter Server password should not contain these special characters($, ', ")
. Make sure the host or the resource pool where the OVA is deployed has the minimum resources mentioned in the link:../deploy/sizing-requirements.html[Prerequisites for deploying ONTAP tools for VMware vSphere] section.
. The login credentials for your vCenter Server instance to which the ONTAP tools for VMware vSphere will connect to post deployment for registration. 
. Delete the browser cache.
. For non-HA deployment, you need three free IP addresses - one free IP address for load balancer and one free IP address for the Kubernetes control plane and one IP address for node. For HA deployment, along with these three IP addresses you'll need two more IP addresses for second and third nodes.
Host names should be mapped to the free IP addresses on the DNS before assigning. All the five IP addresses should be on the same VLAN that is selected for deployment. 
. Content library template once uploaded should not be deleted post deployment as it will be used during reboots.
. In a multi-vCenter deployment where Custom CA certificates are mandatory, map the Domain Name on which the certificate is issued to the Virtual IP address. Perform a _nslookup_ check on the domain name to check whether the domain is getting resolved to the intended IP address. The certificates should be created with domain name and IP address of the load balancer IP address.
. IPv4/IPv6 supported VLAN - Pure IPV6 is not supported. Mixed mode is supported with VLAN having both IPv6 and IPv4 addresses.
. NTP Server which is provided to the vCenter Server for time sync.
. Static IP address Configuration details for the Node or VM where the OVA is being deployed (Mandatory) and other details. 
.. vCenter Server hostname (vCenter where the OVA is deployed)
.. vCenter Server username (vCenter where the OVA is deployed)
.. vCenter Server password (vCenter where the OVA is deployed)
.. Resource pool
.. Data LIF (IPv4/IPv6)
.. Management LIF
.. ONTAP username
.. ONTAP password
.. SVM name
.. Protocol
.. Virtual IP addresses for the Kubernetes control plane. 
.. HA / NON-HA drop down
.. List of hostnames
.. IP addresses (string)
.. Content library name
.. OVF template name
.. IPv6 gateway (optional)



