---
permalink: release-notes/otv-9-otv10-feature-comparison.html
sidebar: sidebar
keywords: release notes, feature, comparison
summary: "Learn about the OTV 9 and OTV 10 feature comparison"
---
= OTV 9 and OTV 10 feature comparison
:icons: font
:imagesdir: ../media/

[.lead]

For the most up-to-date compatibility information, see https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].

[cols="20%,40%,40%",options="header"]
|===
| Feature | ONTAP tools 9.13 | ONTAP tools 10.1
|
Key value proposition
|
Streamline and simplify day-0 to day-2 operations with enhanced security, compliance and automation capabilities
|
Evolving ONTAP tools 10.x towards 9.x parity while extending high availability, performance, and scale limits
|
ONTAP release qualification
|
ONTAP 9.9.1 to ONTAP 9.15.1
|
ONTAP 9.12.1 to ONTAP 9.14.1
|
VMware release support
|
vSphere 7.x-8.x

SRM 8.5-9.0 
|
vSphere 7.x-8.x

SRM 8.7-9.0
|
Protocol support
|
Traditional datastores: NFS (v3 and v4.1), VMFS (iSCSI and FCP)

vVols: iSCSI, FCP, NVMe/FC, NFS v3
|
Traditional datastores: NFS (v3 and v4.1), VMFS (iSCSI)

vVols: iSCSI, NFS v3
|
Scalability
|
Hosts and VMs: 300 Hosts, up to 10K VMs 

Datastores: 600 NFS, up to 50 VMFS, up to 250 vVols

vVols: Up to 14K
|
Hosts and VMs: 600 Hosts

vVols: Up to 140K
|
Observability
|
Performance, capacity, and host compliance dashboards

Dynamic VM and datastore reports
|
Updated performance, capacity, and host compliance dashboards

Dynamic VM and datastore reports
|
Data protection
|
SRA replication for VMFS and NFS

FlexVols based replication for vVols

SCV integration and interoperable for backup
|
SRA replication for iSCSI VMFS and NFS v3 datastores
|===